export { MyCoreModule } from './my-core.module'
export * from './services/logger.service'
export * from './pipes/cadenas.pipe'
export * from './pipes/numericos.pipe'
export * from './components/sizer'
export * from './directives/mis-validadores'
export * from './directives/dates-validators'
